name: Docker Build Workflow

on:
  push:
    branches:
      - master

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Custom Docker Build
        uses: ./github/actions/docker-build
        with:
          image_name: my-service:latest
          context_path: .
