on:

 push:
  branches:
   - master

  

  paths-ignore:
   - ".docs"

 pull_request:
  types:
   - opened


   

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v5.0.0
