name: First Workflow

# triggers - events - push , pull_request , issue , workflow_dispatch , fork , pull_request_review , workflow_call,schedule
on:
 pull_request:
   types:
    - open
jobs:
 build:
  runs-on: ubuntu-latest 
  steps:
   - name: Print 
     run: echo 'build'

 test:
  needs: build
  runs-on: windows-latest 
  steps:
    - name: Print 
      run: echo 'test'

 deploy:
   needs: [ build, test ]
   runs-on: ubuntu-latest 
   steps:
      - name: Print 
        run: echo 'deploy'

 
