name: First Workflow 


on:
 workflow_dispatch:
  inputs:
   TARGET_ENV:
    type: environment
    default: dev


jobs:
 build:
  runs-on: ubuntu-latest
  environment: ${{inputs.TARGET_ENV}}
  steps:
   - name: Print
     run: echo "${{vars.user}}"

 
