name: Reusable Workflow

on:
 workflow_call:

jobs:
 build:
  runs-on: self-host
  steps:
  - name: Checkout
    uses: actions/checkout@v4.2.0
  - name: Run Reusable Build Step
    run: echo 'This is a reusable workflow'
